name: Shell Commands

on: [push]

jobs:
    linux-machine:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello GitHub actions"
            - name: multiline script
              run: |
                  node -v
                  npm -v
            - name: python command
              run: |
                  import platform
                  print(platform.processor())
              shell: python
    windows-machine:
        runs-on: windows-latest
        steps:
            - name: directory powershell
              run: Get-Location
            - name: directory bash
              run: pwd
              shell: bash
    linux-machine-dependent:
        runs-on: ubuntu-latest
        needs: [linux-machine]
        steps:
            - name: echo string
              run: echo "Job 'linux-machine' has completed. Time to start this job."